<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '...' => '...',
    'Afegir' => 'Añadir',
    'Afegir un usuari' => 'Añadir un usuario',
    'Benvingut de nou,' => 'Bienvenido de nuevo,',
    'Castella' => 'Español',
    'Catala' => 'Catalan',
    'Cognoms' => 'Apellidos',
    'Contrassenya' => 'Contraseña',
    'Correu electrònic' => 'Correo electrónico',
    'Dades usuari' => 'Datos del usuario',
    'Desconnectar' => 'Desconectar',
    'Descripció' => 'Descripción',
    'Documents' => 'Documentos',
    'Estas aquí:' => 'Estás aquí:',
    'Filtrar' => 'Filtrar',
    'Foto' => 'Foto',
    'Guardar' => 'Guardar',
    'Imatge' => 'Imagen',
    'Imatges' => 'Imagenes',
    'Imatges i documents' => 'Imagenes y documentos',
    'Informació bàsica' => 'Información básica',
    'Ingles' => 'Ingles',
    'Inici' => 'Inicio',
    'Iniciar sessió ' => 'Iniciar sessión',
    'L\'usuari@ no existeix.' => 'El usuari@ no existe.',
    'La contrassenya no és correcta' => 'La contraseña no és correcta',
    'La seva contrassenya' => 'Su contraseña',
    'Media' => 'Media',
    'Modificar' => 'Modificar',
    'No recordes la teva contrassenya?' => 'No recuerdas tu contraseña?',
    'Nom' => 'Nombre',
    'Nom d\'usuari' => 'Nombre de usuario',
    'Nom del fitxer' => 'Nombre del fitxero',
    'Penjar fitxer' => 'Subir fichero',
    'Perfil' => 'Perfil',
    'Role' => 'Role',
    'Següent' => 'Siguiente',
    'Telefon' => 'Telefono',
    'Totes' => 'Todas',
    'Títol' => 'Titulo',
    'Usuaris' => 'Usuarios',
    'Utilitza el teu compte de vblogv' => 'Utiliza tu cuenta de vblogv',
    'Vols solicitar un compte?' => '¿Quieres solicitar una cuenta?',
    'id' => 'id',
    'Active' => 'Activo',
    'Code' => 'Codigo',
    'Data saved correctly' => 'Datos guardados correctamente',
    'ID' => 'ID',
    'Language' => 'Lenguaje',
    'Loading' => 'Cargando',
    'Logout' => 'Salir',
    'Modify image metadata' => 'Modificar metadatos de la imagen',
    'Name' => 'Nombre',
    'Path to media' => 'Ruta al fichero',
    'Save' => 'Guardar',
    'Sure about leaving?' => 'Estás seguro de salir?',
    'Upload files' => 'Subir ficheros',
    'Users list' => 'Listado de usuarios',
    'no' => 'No',
    'yes' => 'Sí',
    '/' => '@@@@',
    '/login' => '@@@@',
    'logout' => '@@@@',
    'media' => '@@@@',
    'noticia' => '@@@@',
    'noticies' => '@@@@',
    'settings' => '@@@@',
    'user' => '@@@@',
    'users' => '@@@@',
];
