<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '...' => '...',
    'Afegir' => 'Afegir',
    'Afegir un usuari' => 'Afegir un usuari',
    'Benvingut de nou,' => 'Benvingut de nou,',
    'Castella' => 'Castella',
    'Catala' => 'Català',
    'Cognoms' => 'Cognoms',
    'Contrassenya' => 'Contrassenya',
    'Correu electrònic' => 'Correu electrònic',
    'Dades usuari' => 'Dades de l\'usuari',
    'Desconnectar' => 'Desconnectar',
    'Descripció' => 'Descripció',
    'Documents' => 'Documents',
    'Estas aquí:' => 'Estas aquí:',
    'Filtrar' => 'Filtrar',
    'Foto' => 'Foto',
    'Guardar' => 'Guardar',
    'Imatge' => 'Imatge',
    'Imatges' => 'Imatges',
    'Imatges i documents' => 'Imatges i documents',
    'Informació bàsica' => 'Informació bàsica',
    'Ingles' => 'Anglès',
    'Inici' => 'Inici',
    'Iniciar sessió ' => 'Iniciar sessió',
    'L\'usuari@ no existeix.' => 'L\'usuari@ no existeix.',
    'La contrassenya no és correcta' => 'La contrassenya no és correcta',
    'La seva contrassenya' => 'La seva contrassenya',
    'Media' => 'Media',
    'Modificar' => 'Modificar',
    'No recordes la teva contrassenya?' => 'No recordes la teva contrassenya?',
    'Nom' => 'Nom',
    'Nom d\'usuari' => 'Nom d\'usuari',
    'Nom del fitxer' => 'Nom del fitxer',
    'Penjar fitxer' => 'Penjar fitxer',
    'Perfil' => 'Perfil',
    'Role' => 'Role',
    'Següent' => 'Següent',
    'Telefon' => 'Telèfon',
    'Totes' => 'Totes',
    'Títol' => 'Títol',
    'Usuaris' => 'Usuaris',
    'Utilitza el teu compte de vblogv' => 'Utilitza el teu compte de vblogv',
    'Vols solicitar un compte?' => 'Vols sol·licitar un compte?',
    'id' => 'id',
    'Active' => 'Actiu',
    'Code' => 'Codi',
    'Data saved correctly' => 'Dades guardades correctament',
    'ID' => 'ID',
    'Language' => 'Llenguatge',
    'Loading' => 'Carregant',
    'Logout' => 'Sortir',
    'Modify image metadata' => 'Modificar metadades de la imatge',
    'Name' => 'Nom',
    'Path to media' => 'Ruta al fitxer',
    'Save' => 'Guardar',
    'Sure about leaving?' => 'Estas segur de sortir?',
    'Upload files' => 'Pujar fitxers',
    'Users list' => 'Llistat d\'usuaris',
    'no' => 'No',
    'yes' => 'Sí',
    '/' => '@@/@@',
    '/login' => '@@@@',
    'logout' => '@@@@',
    'media' => '@@@@',
    'noticia' => '@@@@',
    'noticies' => '@@@@',
    'settings' => '@@@@',
    'user' => '@@@@',
    'users' => '@@@@',
];
