<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '...' => '...',
    'Afegir' => 'Add',
    'Afegir un usuari' => 'Add an user',
    'Benvingut de nou,' => 'Welcome back,',
    'Castella' => 'Spanish',
    'Catala' => 'Catalan',
    'Cognoms' => 'Surnames',
    'Contrassenya' => 'Password',
    'Correu electrònic' => 'Email',
    'Dades usuari' => 'User data',
    'Desconnectar' => 'Logout',
    'Descripció' => 'Description',
    'Documents' => 'Documents',
    'Estas aquí:' => 'You\'r here:',
    'Filtrar' => 'Filter',
    'Foto' => 'Photo',
    'Guardar' => 'Save',
    'Imatge' => 'Image',
    'Imatges' => 'Images',
    'Imatges i documents' => 'Images and documents',
    'Informació bàsica' => 'Basic information',
    'Ingles' => 'English',
    'Inici' => 'Home',
    'Iniciar sessió ' => 'Login',
    'L\'usuari@ no existeix.' => 'User doesn\'t exist',
    'La contrassenya no és correcta' => 'Password is incorrect',
    'La seva contrassenya' => 'Your password',
    'Media' => 'Media',
    'Modificar' => 'Modify',
    'No recordes la teva contrassenya?' => 'You don\'t remember your password?',
    'Nom' => 'Name',
    'Nom d\'usuari' => 'Username',
    'Nom del fitxer' => 'File name',
    'Penjar fitxer' => 'Upload file',
    'Perfil' => 'Profile',
    'Role' => 'Role',
    'Següent' => 'Next',
    'Telefon' => 'Phone',
    'Totes' => 'All',
    'Títol' => 'Title',
    'Usuaris' => 'Users',
    'Utilitza el teu compte de vblogv' => 'Use your vblogv account!',
    'Vols solicitar un compte?' => 'Do you want an account?',
    'id' => 'id',
    'Active' => 'Active',
    'Code' => 'Code',
    'Data saved correctly' => 'Data saved correctly',
    'ID' => 'ID',
    'Language' => 'Language',
    'Loading' => 'Loading',
    'Logout' => 'Logout',
    'Modify image metadata' => 'Modify image metadata',
    'Name' => 'Name',
    'Path to media' => 'Path to media',
    'Save' => 'Save',
    'Sure about leaving?' => 'Are you sure about leaving?',
    'Upload files' => 'Upload files',
    'Users list' => 'Users list',
    'no' => 'No',
    'yes' => 'Yes',
    '/' => '@@@@',
    '/login' => '@@@@',
    'logout' => '@@@@',
    'media' => '@@@@',
    'noticia' => '@@@@',
    'noticies' => '@@@@',
    'settings' => '@@@@',
    'user' => '@@@@',
    'users' => '@@@@',
];
